<template>
  <div class="background">
    <div class="common_popup">
      <!-- scroll -->
      <div class="scroll_area">
        <div class="scroll_content_area">
          <div style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: 1.5; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 12px;"><span style="font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 12px; font-style: initial; font-variant-ligatures: initial; font-variant-caps: initial; font-weight: initial;">​</span><br></div>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 14pt;">LINE FRIENDS</span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; color: rgb(0, 191, 22); letter-spacing: -0.1pt; font-size: 14pt;"></span></span><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; color: rgb(0, 191, 22); letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 14pt;">온라인</span></span><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; color: rgb(0, 191, 22); letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 14pt;">&nbsp;스토어 운영 종료<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">&nbsp;</span></span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 14pt;">안내입니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.</span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;">&nbsp;</span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">안녕하세요<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">,</span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">라인프렌즈 온라인 스토어입니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.&nbsp;</span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;">&nbsp;</span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">먼저<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">,&nbsp;</span>그동안 라인프렌즈 온라인 스토어를 이용해주신 고객님들께 진심으로 감사드립니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.</span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">라인프렌즈 온라인 스토어가 보다 편리하고 새로운 서비스를 제공하기 위해</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">라인프렌즈 스마트 스토어로 통합됩니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.</span></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">이에<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">,&nbsp;</span>온라인 스토어 운영 종료 일정을 안내드리오니 이용에 참고해 주시길 바랍니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.&nbsp;</span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;">&nbsp;</span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 191, 22); letter-spacing: -0.1pt; font-family: 나눔고딕;">[</span></span><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 191, 22); letter-spacing: -0.1pt; font-family: 나눔고딕;">온라인 스토어 운영 종료 일시<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">]</span></span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">&nbsp;</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">2019</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">년<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">&nbsp;9</span>월<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">&nbsp;30</span>일<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">&nbsp;18</span>시&nbsp;<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">00</span>분</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: black; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">※</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">9</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">월&nbsp;</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">30</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">일&nbsp;</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">18:00&nbsp;</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">이후 상품 구매가 불가합니다</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: NanumGothic, 나눔고딕, sans-serif; font-size: 10pt;">.</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;">&nbsp;</span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 191, 22); letter-spacing: -0.1pt; font-family: 나눔고딕;">[</span></span><span style="box-sizing: initial; font-weight: 700; margin: 0px; padding: 0px; border: 0px; line-height: normal; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 191, 22); letter-spacing: -0.1pt; font-family: 나눔고딕;">라인프렌즈 스마트 스토어<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">]</span></span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">&nbsp;</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; font-family: &quot;맑은 고딕&quot;; font-size: 10pt;"><a href="https://smartstore.naver.com/linefriends" target="_blank" rel="noreferrer noopener" style="box-sizing: initial; color: rgb(51, 122, 183); margin: 0px; padding: 0px; border: 0px; line-height: inherit; cursor: pointer; text-decoration-skip-ink: none;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(85, 26, 139);"></span></a><a href="https://smartstore.naver.com/linefriends" target="_blank" rel="noreferrer noopener" style="box-sizing: initial; color: rgb(51, 122, 183); margin: 0px; padding: 0px; border: 0px; line-height: inherit; cursor: pointer; text-decoration-skip-ink: none;">https://smartstore.naver.com/linefriends</a></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;">&nbsp;</span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">온라인 스토어 가입 시 제출한 개인정보는 관계법령의 규정에 의해<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;"></span></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">일정 기간 동안만 보존되며<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">,&nbsp;</span>이후 즉시 파기됩니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.</span></span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">&nbsp;</span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">기타 궁금하신 사항은<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">&nbsp;LINE FRIENDS Customer Care (1544-5921,&nbsp;customercare@linefriends.com)</span>으로</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">문의 주시면 신속하게 확인 후 답변드리겠습니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.</span></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">&nbsp;</span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">감사합니다<span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none;">.</span></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔고딕; font-size: 10pt;">라인프렌즈 드림</span><span style="box-sizing: initial; margin: 0px; padding: 0px; border: 0px; line-height: inherit; text-decoration-skip-ink: none; letter-spacing: -0.1pt; font-family: 나눔바른고딕; font-size: 10.5pt;"></span></p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">​</p>
          <p align="left" style="box-sizing: initial; margin: 0cm; border: 0px; line-height: normal; text-decoration-skip-ink: none; unicode-bidi: embed; color: rgb(51, 51, 51); font-family: NanumGothic, 나눔고딕, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><br></p>
        </div>
      </div>
      <div class="foot_area">
        <div class="checkbox_area">
          <span class="bx_input">
            <input v-model="flag" id="personal-5" type="checkbox" />
            <label class="txt_2" for="personal-5">다시 보지 않기</label>
          </span>
        </div>
        <div class="btn_area">
          <button @click="ClosePopup">닫기</button>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import { mapGetters } from 'vuex'
import cookies from 'js-cookie'
export default {
  data () {
    return {
      isCommonPopup: true,
      flag: false
    }
  },
  computed: {
    ...mapGetters('profile', ['memberId'])
  },
  methods: {
    ClosePopup () {
      this.isCommonPopup = false
      this.sendIsClose()
      cookies.set('CommonPopupIsOpen', !this.flag)
    },
    sendIsClose () {
      this.$emit('isCloseCommonPopup', this.isCommonPopup)
    }
  },
  mounted () {
    this.isLogin = cookies.get('111111')
  }
}
</script>